---

- name: Install basic packages
  become: true
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - vim
    - python3-minimal
    - python-minimal
    - iputils-ping
    - sudo
    - iotop