---
- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart ssh

- name: Enable ssh pubkey login
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PubkeyAuthentication"
              line="PubkeyAuthentication yes"
              state=present
  notify: Restart ssh