---
kind: pipeline
name: packer
type: docker

steps:
- name: terraform
  image: hashicorp/terraform:0.12.12
  commands:
    - cd packer/terraform
    - terraform init
    - terraform apply --auto-approve
    - terraform output amis > /shared/ami.json
  volumes:
  - name: shared
    path: /shared
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key

- name: packer
  image: quay.io/sighup/packer:2.8.5_10_1.4.4
  commands:
    - cd packer
    - packer build /shared/ami.json
  volumes:
  - name: shared
    path: /shared
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key

volumes:
- name: shared
  temp: {}

trigger:
  branch:
    - feature/auto-join