---

- name: Installing AWS dependencies
  include_tasks: "aws.yml"

- name: Installing container runtime
  include_tasks: "{{ container_runtime }}.yml"

- name: Installing Kubelet Kubeadm Kubectl Critools
  include_tasks: "kubelet.yml"