---
kubeadm_config_file: /etc/kubernetes/kubeadm.yml
audit_log_dir: /var/log/kubernetes
audit_policy_max_age: 3
audit_policy_config_path: /etc/kubernetes/audit.yaml

## MasterConfig paramethers
kubernetes_pod_cidr: "10.32.0.0/16"
kubernetes_svc_cidr: "10.96.0.0/16"
kubernetes_cluster_name: "sighup-prod"
kubernetes_cloud_provider: "aws"
kubernetes_api_SAN:
  - localhost
  - kubernetes.local
kubernetes_version: "1.14.3"
kubernetes_hostname: "{{ ansible_fqdn }}"
kubernetes_kubeconfig_path: "."
kubernetes_users_names: []
kubernetes_users_org: sighup
kubernetes_users_kubeconfig_dir: /etc/kubernetes/users
kubernetes_control_plane_address: "{{ ansible_hostname }}"
etcd:
  endpoints:
    - "https://127.0.0.1:2379"
  caFile: '/etc/etcd/pki/etcd/ca.crt'
  keyFile: '/etc/etcd/pki/apiserver-etcd-client.key'
  certFile: '/etc/etcd/pki/apiserver-etcd-client.crt'

## OIDC
oidc_isssuer_url: ""
oidc_client_id: ""
oidc_username_claim: email
oidc_groups_claim: groups
oidc_group_prefix: oidc

