- name: Kubernetes node preparation
  hosts: all
  become: true
  vars:
    kubernetes_repo_distribution: 'xenial'
    kubernetescni_version: '0.7.5'
    docker_version: '18.06.3~ce~3-0~ubuntu'
  roles:
    - ../../roles/kube-node-common

- name: Installing and configuring furyagent
  hosts: all
  become: true
  vars:
    furyagent_uri: https://github.com/sighupio/furyagent/releases/download/v0.0.5/furyagent-linux-amd64
  tasks:
  - name: Installing furyagent
    get_url:
      url: "{{ furyagent_uri }}"
      dest: /usr/local/bin/furyagent
      mode: 0750
      force: yes
