---
# CRI
container_runtime: docker
docker_version: 18.06.2~ce~3-0~ubuntu

# Kurnetes Components Versions
kubernetes_repo_distribution: 'xenial'
kubelet_version: '1.15.4'
kubectl_version: '1.15.4'
kubeadm_version: '1.15.4'
critools_version: '1.15.0'
kubernetescni_version: '0.7.5'
kubernetes_cloud_provider: 'aws'
# Docker Configurations
# registry_mirrors:
# - ""
# docker_dns:
# - ""
