---
# CRI
container_runtime: docker
docker_version: 18.06.2~ce~3-0~ubuntu

# Kurnetes Components Versions
kubernetes_repo_distribution: 'xenial'
kubelet_version: '1.15.4'
kubectl_version: '1.15.4'
kubeadm_version: '1.15.4'
critools_version: '1.15.0'
# critools variables
critools:
  v1.14.0:
    crictl:
      sha256: 483c90a9fe679590df4332ba807991c49232e8cd326c307c575ecef7fe22327b
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 4c640219e297c877b56e7b13dcd0f10ab2a76092dd7bdb888d83c64372f0a3f9
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
  v1.15.0:
    crictl:
      sha256: c3b71be1f363e16078b51334967348aab4f72f46ef64a61fe7754e029779d45a
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 099ac7f169b2c1b080448788b21969118659a24cd345e16836a4c959b95493e5
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
  v1.16.0:
    crictl:
      sha256: a3eefa10a483c643ad85aee3d7832a720976ef7e80dde46b212eaaacd7d09512
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
    critest:
      sha256: 909ba3e1404c86b82a957d4c69ae9a40e418a09e104fc017e708b877f78eaa73
      base_url: https://github.com/kubernetes-sigs/cri-tools/releases/download
kubernetescni_version: '0.7.5'
kubernetes_cloud_provider: 'aws'
# Docker Configurations
# registry_mirrors:
# - ""
# docker_dns:
# - ""
